server {
    listen 80;
    
    # Raíz donde están los archivos estáticos
    root /usr/share/nginx/html;
    index index.html;

    # Manejo de rutas para React Router (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para recursos estáticos (opcional pero recomendado)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
