services:
  db:
    image: postgres:15-alpine
    container_name: blog-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: blog_seguro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: blog-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        # Por defecto usará desarrollo, pero lo podemos sobreescribir
        - MODE=development
    container_name: blog-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: