services:
  db:
    image: postgres:15-alpine
    container_name: blog-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: blog-backend
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # Por defecto usará desarrollo, pero lo podemos sobreescribir
        - MODE=development
    container_name: blog-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_agent
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

volumes:
  postgres_data:
